### ISSUE TITLE
Use POI 3.17

### ISSUE THREAD

**Issue by jpequery** [jpequery/EMFSpreadsheetIO#11]
As m2doc will use POI 3.17 in its 2.0 release, we shall use this new revision.

reference : https://github.com/ObeoNetwork/M2Doc/pull/257

**Comment by ylussaud** [comment]
I moved ObeoNetwork/Bits to POI 3.17 and ObeoNetwork/M2Doc will follow soon.

**Comment by jpequery** [comment]
Updated to POI 4.10 from m2doc 3.1.1
