### ISSUE TITLE
Export procedure

### ISSUE THREAD

**Issue by caesarfive** [jpequery/EMFSpreadsheetIO#12]
Hi,
I installed EMFSpreadsheetIO plugin on Capella 1.2 and tried to export some project elements(function exchange and component exchange) . I followed the procedure described in the doc but after the selection of category that I wanted export,  pushing OK nothing happens. I expected that a popup menu required me where do save the Excel File. I also tried to import in the work_space of the project an empty Excel file but if I select the empty file and an element of Capella project in the Explorer menu the contextual menu allow me only to select the Import functionality.  May you kindly explain what I'm doing wrong?

**Comment by caesarfive** [comment]
Found the export xlsx file in the project repository having the project name for the sheet.

**Comment by jpequery** [comment]
Hello, sorry for the delay, but you found yourself the solution. Note that I need to add a refresh after the export.
